[package]
name = "adw-user-colors-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = { version = "0.6", features = ["serializing"] }
anyhow = "1.0"
gtk4 = { version = "0.4.8", features = ["v4_4"] }
adw = {version = "0.1.1", package = "libadwaita"}
relm4-macros = { git = "https://github.com/AaronErhardt/Relm4"}
once_cell = "1.9.0"
tokio = { version = "1.17.0", features = ["full"] }
cascade = "1.0.0"
float-cmp = "0.9.0"
hex = "0.4.3"
user-colors = { path = "../adw-user-colors-lib", package = "adw-user-colors-lib" }
serde = "1.0.136"
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
xdg = "2.4.1"
# kmeans_colors = { git = "https://github.com/okaneco/kmeans-colors", features = ["palette_color"], default-features = false }

[build-dependencies]
gio = "0.15.10"